#!/bin/sh
#
YES=0

function err_exit {
   if [ -n "$1" ]; then
      echo "$1"
   else
      echo "Usage: $0 [ -s ORACLE_SID | -y ]"
   fi
   if [ -n "$2" ]; then
      exit $2
   else
      exit 1
   fi
}

while getopts "s:y" opt
do
  case $opt in
    s)
      export ORACLE_SID=$OPTARG
      ;;
    y)
      YES=1
      ;;
    \?)
      err_exit
      ;;
  esac
done

if [ -z "$(cut -d: -f 1 /etc/oratab | grep $ORACLE_SID)" ]; then
   err_exit "DB Instance $ORACLE_SID not found in /etc/oratab."
fi

ORAENV_ASK=NO
source oraenv

if [ "$YES" -ne 1 ]; then
   echo -n "Shutdown database $ORACLE_SID [y/n]? "
   read ANSWER
   if [ "$ANSWER" != "y" -a "$ANSWER" != "Y" ]; then
      exit
   fi
fi

if [ -z "$(ps -ef |grep ora_pmon_$ORACLE_SID | grep -v grep | awk '{print $NF}')" ]; then
   echo "Database already shutdown."
   exit
fi

sqlplus -S / as sysdba <<EOF
whenever sqlerror exit 1
set heading off;
set pagesize 0;
set feedback off;
shutdown immediate
EOF

if [ "$?" -eq 0 ]; then
   echo "$ORACLE_SID shutdown"
else
   err_exit "Database not shutdown."
fi
