#!/bin/sh
#
SCRIPTDIR=$(cd $(dirname $0) && pwd)
source $SCRIPTDIR/lib/libcommon.sh
YES=0
SKIPENV=0
SHUTDOWN_MODE="immediate"
PRINT_USAGE="Usage: $0 -s SID [ -y | -e | -f ]
           -s Oracle SID
           -y Assume yes response to confirmation prompt
           -e Skip environment setup (current environment must be setup)
           -f Force shutdown (shutdown abort)"

while getopts "s:yef" opt
do
  case $opt in
    s)
      export ORACLE_SID=$OPTARG
      ;;
    y)
      YES=1
      ;;
    e)
      SKIPENV=1
      ;;
    f)
      SHUTDOWN_MODE="abort"
      ;;
    \?)
      err_exit
      ;;
  esac
done

if [ "$SKIPENV" -eq 0 ]; then
   if [ -z "$(cut -d: -f 1 /etc/oratab | grep $ORACLE_SID)" ]; then
      err_exit "DB Instance $ORACLE_SID not found in /etc/oratab."
   fi
   ORAENV_ASK=NO
   source oraenv
fi

if [ "$YES" -ne 1 ]; then
   echo -n "Shutdown database $ORACLE_SID [y/n]? "
   read ANSWER
   if [ "$ANSWER" != "y" -a "$ANSWER" != "Y" ]; then
      exit
   fi
fi

if [ -z "$(ps -ef |grep ora_pmon_$ORACLE_SID | grep -v grep | awk '{print $NF}')" ]; then
   echo "Database already shutdown."
   exit
fi

sqlCommand="shutdown $SHUTDOWN_MODE"
echo -n "Shutting instance $ORACLE_SID down ..."
result=$(run_query "$sqlCommand")
echo "Done."
